### ISSUE TITLE
Consider moving to absolute links in footer

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/mitlib-style#34]
non-core sites (i.e. everything that isn't in the libraries.mit.edu domain) need to change all the links to include https://libraries.mit.edu because the links are relative. There isn't much harm is just hard-coding https://libraries.mit.edu. The only real downside is if someone needed to be on the non-ssl site for some reason (at which point we should probably fix the reason that is desired).

**Comment by JPrevost** [comment]
I think this has been resolved? @frrrances ?

**Comment by frrrances** [comment]
Yes: https://github.com/MITLibraries/mitlib-style/pull/36
